# ./docker-compose.yml
version: "3.9"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "8000"                       # internal only; not published
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging: *default-logging

  caddy:
    image: caddy:2
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data          # cert cache
      - caddy_config:/config
    restart: unless-stopped
    logging: *default-logging

volumes:
  caddy_data:
  caddy_config:
